--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

-- Singleton state for the server-side first-administrator bootstrap. The
-- bootstrap secret itself is an Edge Function secret and is never persisted.
create table private.first_admin_bootstrap (
    singleton boolean primary key default true,
    state text not null default 'pending',
    claim_id uuid,
    claimed_at timestamp with time zone,
    completed_at timestamp with time zone,
    admin_user_id uuid,
    constraint first_admin_bootstrap_singleton check (singleton),
    constraint first_admin_bootstrap_state check (state in ('pending', 'claimed', 'completed')),
    constraint first_admin_bootstrap_claim_shape check (
      (state = 'pending' and claim_id is null and claimed_at is null and completed_at is null and admin_user_id is null)
      or (state = 'claimed' and claim_id is not null and claimed_at is not null and completed_at is null and admin_user_id is null)
      or (state = 'completed' and completed_at is not null)
    )
);

insert into private.first_admin_bootstrap (
    singleton,
    state,
    completed_at,
    admin_user_id
)
select
    true,
    case when existing_user.id is null then 'pending' else 'completed' end,
    case when existing_user.id is null then null else now() end,
    existing_user.id
from (
    select au.id
    from auth.users au
    order by au.created_at, au.id
    limit 1
) existing_user
right join (select true) seed on true;

-- Short-lived, service-issued capabilities used while GoTrue performs the
-- initial auth.users INSERT. Only the opaque UUID is carried in user metadata.
create table private.user_provisioning_claims (
    claim_id uuid primary key,
    email text not null,
    purpose text not null,
    administrator boolean not null,
    created_at timestamp with time zone not null default now(),
    expires_at timestamp with time zone not null,
    constraint user_provisioning_claims_email_normalized_check check (email = lower(btrim(email)) and length(email) between 3 and 254),
    constraint user_provisioning_claims_purpose_check check (purpose in ('bootstrap', 'administrator')),
    constraint user_provisioning_claims_expiry_check check (expires_at > created_at)
);

create table public.companies (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    name text not null,
    normalized_name text not null default '',
    deduplication_key text not null default '',
    unified_social_credit_code extensions.citext,
    registration_number text,
    organization_code text,
    legal_representative text,
    operating_status text,
    company_type text,
    registered_capital_amount numeric(20, 2),
    paid_in_capital_amount numeric(20, 2),
    registered_capital_currency text not null default 'CNY',
    established_on date,
    approved_on date,
    registration_authority text,
    business_scope text,
    province text,
    district text,
    industry_code text,
    industry_name text,
    employee_count integer,
    insured_employee_count integer,
    personnel_scale_text text,
    region_text text,
    primary_source text,
    last_verified_at timestamp with time zone,
    profile_status text not null default 'unverified',
    completeness_score numeric(5, 4),
    merged_into_company_id bigint,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb,
    constraint companies_workspace_id_id_key unique (workspace_id, id),
    constraint companies_workspace_deduplication_key_key unique (workspace_id, deduplication_key),
    constraint companies_workspace_uscc_key unique (workspace_id, unified_social_credit_code),
    constraint companies_registered_capital_nonnegative check (registered_capital_amount is null or registered_capital_amount >= 0),
    constraint companies_paid_in_capital_nonnegative check (paid_in_capital_amount is null or paid_in_capital_amount >= 0),
    constraint companies_employee_count_nonnegative check (employee_count is null or employee_count >= 0),
    constraint companies_insured_employee_count_nonnegative check (insured_employee_count is null or insured_employee_count >= 0),
    constraint companies_profile_status_check check (profile_status in ('unverified', 'verified', 'conflicted', 'merged', 'archived')),
    constraint companies_completeness_score_check check (completeness_score is null or (completeness_score >= 0 and completeness_score <= 1))
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.companies
    add constraint companies_workspace_id_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict;

alter table public.companies
    add constraint companies_merged_into_company_fkey foreign key (workspace_id, merged_into_company_id) references public.companies(workspace_id, id) on delete restrict;

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);
create index companies_workspace_updated_idx on public.companies (workspace_id, updated_at desc);
create index companies_workspace_normalized_name_idx on public.companies (workspace_id, normalized_name);
create index companies_workspace_status_idx on public.companies (workspace_id, profile_status, operating_status);

--
-- Enterprise list workbench production domain
--

create table public.field_mapping_sets (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    provider text not null,
    name text not null,
    description text,
    status text not null default 'draft',
    is_locked boolean not null default false,
    current_version_number integer,
    created_by uuid,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint field_mapping_sets_workspace_id_id_key unique (workspace_id, id),
    constraint field_mapping_sets_workspace_name_key unique (workspace_id, provider, name),
    constraint field_mapping_sets_provider_check check (provider in ('qcc', 'huoke_assistant', 'file_upload', 'web_search', 'other')),
    constraint field_mapping_sets_status_check check (status in ('draft', 'active', 'archived')),
    constraint field_mapping_sets_version_positive check (current_version_number is null or current_version_number > 0),
    constraint field_mapping_sets_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint field_mapping_sets_created_by_fkey foreign key (created_by) references auth.users(id) on delete set null
);

create table public.field_mapping_versions (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    mapping_set_id uuid not null,
    version_number integer not null,
    status text not null default 'draft',
    is_locked boolean not null default false,
    mapping_definition jsonb not null,
    source_schema_version text,
    canonical_schema_version text not null default '1.0',
    change_note text,
    created_by uuid,
    created_at timestamp with time zone not null default now(),
    published_at timestamp with time zone,
    constraint field_mapping_versions_workspace_id_id_key unique (workspace_id, id),
    constraint field_mapping_versions_set_version_key unique (workspace_id, mapping_set_id, version_number),
    constraint field_mapping_versions_version_positive check (version_number > 0),
    constraint field_mapping_versions_status_check check (status in ('draft', 'published', 'retired')),
    constraint field_mapping_versions_definition_object check (jsonb_typeof(mapping_definition) = 'object'),
    constraint field_mapping_versions_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint field_mapping_versions_mapping_set_fkey foreign key (workspace_id, mapping_set_id) references public.field_mapping_sets(workspace_id, id) on delete restrict,
    constraint field_mapping_versions_created_by_fkey foreign key (created_by) references auth.users(id) on delete set null
);

create table public.source_connections (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    provider text not null,
    name text not null,
    connection_kind text not null,
    status text not null default 'draft',
    secret_reference text,
    has_secret_reference boolean generated always as (secret_reference is not null) stored,
    connection_config jsonb not null default '{}'::jsonb,
    capabilities text[] not null default '{}',
    default_mapping_version_id uuid,
    external_connection_id text,
    last_verified_at timestamp with time zone,
    last_error_code text,
    created_by uuid,
    updated_by uuid,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint source_connections_workspace_id_id_key unique (workspace_id, id),
    constraint source_connections_workspace_name_key unique (workspace_id, name),
    constraint source_connections_provider_check check (provider in ('qcc', 'huoke_assistant', 'file_upload', 'web_search', 'other')),
    constraint source_connections_kind_check check (connection_kind in ('mcp', 'api', 'cli', 'upload', 'web_search', 'other')),
    constraint source_connections_status_check check (status in ('draft', 'ready', 'degraded', 'disabled', 'error')),
    constraint source_connections_name_not_blank check (btrim(name) <> ''),
    constraint source_connections_secret_reference_format check (
        secret_reference is null
        or secret_reference ~ '^[a-z][a-z0-9+.-]*://[^[:space:]]+$'
    ),
    constraint source_connections_config_object check (jsonb_typeof(connection_config) = 'object'),
    constraint source_connections_no_inline_secrets check (
        connection_config::text !~* '"(api[_-]?key|access[_-]?token|refresh[_-]?token|client[_-]?secret|password|authorization|private[_-]?key)"[[:space:]]*:'
    ),
    constraint source_connections_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint source_connections_mapping_version_fkey foreign key (workspace_id, default_mapping_version_id) references public.field_mapping_versions(workspace_id, id) on delete restrict,
    constraint source_connections_created_by_fkey foreign key (created_by) references auth.users(id) on delete set null,
    constraint source_connections_updated_by_fkey foreign key (updated_by) references auth.users(id) on delete set null
);

create table public.source_queries (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    source_connection_id uuid not null,
    query_kind text not null,
    query_text text,
    criteria jsonb not null default '{}'::jsonb,
    criteria_hash text not null,
    status text not null default 'draft',
    external_query_id text,
    idempotency_key text,
    requested_by uuid,
    approved_by uuid,
    approved_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint source_queries_workspace_id_id_key unique (workspace_id, id),
    constraint source_queries_workspace_id_connection_key unique (workspace_id, id, source_connection_id),
    constraint source_queries_workspace_idempotency_key unique (workspace_id, idempotency_key),
    constraint source_queries_kind_check check (query_kind in ('company_search', 'company_detail', 'risk_enrichment', 'qualification_enrichment', 'tender_search', 'file_import', 'web_evidence', 'other')),
    constraint source_queries_status_check check (status in ('draft', 'pending_approval', 'approved', 'running', 'completed', 'failed', 'cancelled')),
    constraint source_queries_criteria_object check (jsonb_typeof(criteria) = 'object'),
    constraint source_queries_hash_not_blank check (btrim(criteria_hash) <> ''),
    constraint source_queries_idempotency_format check (
        idempotency_key is null
        or (length(idempotency_key) between 16 and 128 and idempotency_key ~ '^[A-Za-z0-9._:-]+$')
    ),
    constraint source_queries_no_inline_secrets check (
        criteria::text !~* '"(api[_-]?key|access[_-]?token|refresh[_-]?token|client[_-]?secret|password|authorization|private[_-]?key)"[[:space:]]*:'
    ),
    constraint source_queries_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint source_queries_connection_fkey foreign key (workspace_id, source_connection_id) references public.source_connections(workspace_id, id) on delete restrict,
    constraint source_queries_requested_by_fkey foreign key (requested_by) references auth.users(id) on delete set null,
    constraint source_queries_approved_by_fkey foreign key (approved_by) references auth.users(id) on delete set null
);

create table public.ingestion_jobs (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    source_connection_id uuid not null,
    source_query_id uuid,
    mapping_version_id uuid,
    job_kind text not null,
    status text not null default 'queued',
    idempotency_key text not null,
    external_job_id text,
    input_object_path text,
    input_params jsonb not null default '{}'::jsonb,
    requested_by uuid,
    requested_at timestamp with time zone not null default now(),
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    received_count integer not null default 0,
    accepted_count integer not null default 0,
    rejected_count integer not null default 0,
    error_code text,
    error_message text,
    metrics jsonb not null default '{}'::jsonb,
    result jsonb not null default '{}'::jsonb,
    worker_id text,
    claimed_at timestamp with time zone,
    attempt_count integer not null default 0,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint ingestion_jobs_workspace_id_id_key unique (workspace_id, id),
    constraint ingestion_jobs_workspace_id_connection_key unique (workspace_id, id, source_connection_id),
    constraint ingestion_jobs_workspace_idempotency_key unique (workspace_id, idempotency_key),
    constraint ingestion_jobs_kind_check check (job_kind in ('query', 'import', 'enrich', 'refresh', 'connection_test')),
    constraint ingestion_jobs_status_check check (status in ('queued', 'running', 'completed', 'partial', 'failed', 'cancelled')),
    constraint ingestion_jobs_idempotency_format check (length(idempotency_key) between 16 and 128 and idempotency_key ~ '^[A-Za-z0-9._:-]+$'),
    constraint ingestion_jobs_counts_nonnegative check (received_count >= 0 and accepted_count >= 0 and rejected_count >= 0),
    constraint ingestion_jobs_counts_consistent check (accepted_count + rejected_count <= received_count),
    constraint ingestion_jobs_time_order check (completed_at is null or started_at is null or completed_at >= started_at),
    constraint ingestion_jobs_metrics_object check (jsonb_typeof(metrics) = 'object'),
    constraint ingestion_jobs_result_object check (jsonb_typeof(result) = 'object'),
    constraint ingestion_jobs_input_params_object check (jsonb_typeof(input_params) = 'object'),
    constraint ingestion_jobs_no_inline_secrets check (
        input_params::text !~* '"(api[_-]?key|access[_-]?token|refresh[_-]?token|client[_-]?secret|password|authorization|private[_-]?key)"[[:space:]]*:'
    ),
    constraint ingestion_jobs_attempt_count_nonnegative check (attempt_count >= 0),
    constraint ingestion_jobs_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint ingestion_jobs_connection_fkey foreign key (workspace_id, source_connection_id) references public.source_connections(workspace_id, id) on delete restrict,
    constraint ingestion_jobs_query_fkey foreign key (workspace_id, source_query_id, source_connection_id) references public.source_queries(workspace_id, id, source_connection_id) on delete restrict,
    constraint ingestion_jobs_mapping_version_fkey foreign key (workspace_id, mapping_version_id) references public.field_mapping_versions(workspace_id, id) on delete restrict,
    constraint ingestion_jobs_requested_by_fkey foreign key (requested_by) references auth.users(id) on delete set null
);

create table public.source_records (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    ingestion_job_id uuid not null,
    source_connection_id uuid not null,
    source_record_key text not null,
    record_kind text not null,
    raw_payload jsonb not null,
    content_hash text not null,
    source_observed_at timestamp with time zone,
    captured_at timestamp with time zone not null default now(),
    created_at timestamp with time zone not null default now(),
    constraint source_records_workspace_id_id_key unique (workspace_id, id),
    constraint source_records_job_record_key unique (workspace_id, ingestion_job_id, source_record_key),
    constraint source_records_key_not_blank check (btrim(source_record_key) <> ''),
    constraint source_records_kind_not_blank check (btrim(record_kind) <> ''),
    constraint source_records_hash_not_blank check (btrim(content_hash) <> ''),
    constraint source_records_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint source_records_job_fkey foreign key (workspace_id, ingestion_job_id, source_connection_id) references public.ingestion_jobs(workspace_id, id, source_connection_id) on delete restrict,
    constraint source_records_connection_fkey foreign key (workspace_id, source_connection_id) references public.source_connections(workspace_id, id) on delete restrict
);

create table public.source_snapshots (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    source_record_id uuid not null,
    mapping_version_id uuid,
    company_id bigint,
    canonical_schema_version text not null default '1.0',
    normalized_payload jsonb not null,
    content_hash text not null,
    match_status text not null default 'unmatched',
    mapping_warnings jsonb not null default '[]'::jsonb,
    captured_at timestamp with time zone not null default now(),
    created_at timestamp with time zone not null default now(),
    constraint source_snapshots_workspace_id_id_key unique (workspace_id, id),
    constraint source_snapshots_source_hash_key unique (workspace_id, source_record_id, canonical_schema_version, content_hash),
    constraint source_snapshots_match_status_check check (match_status in ('unmatched', 'matched', 'conflict', 'rejected')),
    constraint source_snapshots_payload_object check (jsonb_typeof(normalized_payload) = 'object'),
    constraint source_snapshots_warnings_array check (jsonb_typeof(mapping_warnings) = 'array'),
    constraint source_snapshots_hash_not_blank check (btrim(content_hash) <> ''),
    constraint source_snapshots_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint source_snapshots_record_fkey foreign key (workspace_id, source_record_id) references public.source_records(workspace_id, id) on delete restrict,
    constraint source_snapshots_mapping_version_fkey foreign key (workspace_id, mapping_version_id) references public.field_mapping_versions(workspace_id, id) on delete restrict,
    constraint source_snapshots_company_fkey foreign key (workspace_id, company_id) references public.companies(workspace_id, id) on delete restrict
);

create table public.company_identifiers (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    company_id bigint not null,
    identifier_type text not null,
    identifier_value text not null,
    normalized_value text not null,
    source_provider text not null,
    source_record_id uuid,
    is_primary boolean not null default false,
    first_seen_at timestamp with time zone not null default now(),
    last_seen_at timestamp with time zone not null default now(),
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint company_identifiers_workspace_id_id_key unique (workspace_id, id),
    constraint company_identifiers_company_value_key unique (workspace_id, company_id, identifier_type, normalized_value),
    constraint company_identifiers_type_check check (identifier_type in ('unified_social_credit_code', 'registration_number', 'organization_code', 'taxpayer_id', 'qcc_key_no', 'huoke_company_id', 'website_domain', 'other')),
    constraint company_identifiers_value_not_blank check (btrim(identifier_value) <> '' and btrim(normalized_value) <> ''),
    constraint company_identifiers_source_not_blank check (btrim(source_provider) <> ''),
    constraint company_identifiers_seen_order check (last_seen_at >= first_seen_at),
    constraint company_identifiers_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint company_identifiers_company_fkey foreign key (workspace_id, company_id) references public.companies(workspace_id, id) on delete restrict,
    constraint company_identifiers_source_record_fkey foreign key (workspace_id, source_record_id) references public.source_records(workspace_id, id) on delete restrict
);

create unique index company_identifiers_unique_registry_value_idx
    on public.company_identifiers (workspace_id, identifier_type, normalized_value)
    where identifier_type <> 'website_domain';

create unique index company_identifiers_one_primary_type_idx
    on public.company_identifiers (workspace_id, company_id, identifier_type)
    where is_primary;

create table public.company_evidence (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    company_id bigint not null,
    evidence_type text not null,
    title text not null,
    source_provider text not null,
    source_record_id uuid,
    source_snapshot_id uuid,
    source_url text,
    excerpt text,
    evidence_fingerprint text not null,
    evidence_status text not null default 'unverified',
    observed_at timestamp with time zone,
    captured_at timestamp with time zone not null default now(),
    expires_at timestamp with time zone,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamp with time zone not null default now(),
    constraint company_evidence_workspace_id_id_key unique (workspace_id, id),
    constraint company_evidence_company_fingerprint_key unique (workspace_id, company_id, evidence_fingerprint),
    constraint company_evidence_type_check check (evidence_type in ('registration', 'operation', 'risk', 'qualification', 'tender', 'web', 'uploaded_document', 'manual_note', 'other')),
    constraint company_evidence_status_check check (evidence_status in ('unverified', 'verified', 'stale', 'rejected')),
    constraint company_evidence_title_not_blank check (btrim(title) <> ''),
    constraint company_evidence_source_not_blank check (btrim(source_provider) <> ''),
    constraint company_evidence_fingerprint_not_blank check (btrim(evidence_fingerprint) <> ''),
    constraint company_evidence_metadata_object check (jsonb_typeof(metadata) = 'object'),
    constraint company_evidence_expiry_order check (expires_at is null or expires_at >= captured_at),
    constraint company_evidence_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint company_evidence_company_fkey foreign key (workspace_id, company_id) references public.companies(workspace_id, id) on delete restrict,
    constraint company_evidence_source_record_fkey foreign key (workspace_id, source_record_id) references public.source_records(workspace_id, id) on delete restrict,
    constraint company_evidence_source_snapshot_fkey foreign key (workspace_id, source_snapshot_id) references public.source_snapshots(workspace_id, id) on delete restrict
);

create table public.company_field_facts (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    company_id bigint not null,
    field_name text not null,
    value_json jsonb not null,
    value_text text,
    value_type text not null,
    source_provider text not null,
    source_record_id uuid,
    source_snapshot_id uuid,
    evidence_id uuid,
    confidence numeric(5, 4),
    observed_at timestamp with time zone,
    valid_from timestamp with time zone,
    valid_to timestamp with time zone,
    is_current boolean not null default true,
    idempotency_key text not null,
    created_at timestamp with time zone not null default now(),
    constraint company_field_facts_workspace_id_id_key unique (workspace_id, id),
    constraint company_field_facts_workspace_idempotency_key unique (workspace_id, idempotency_key),
    constraint company_field_facts_field_not_blank check (btrim(field_name) <> ''),
    constraint company_field_facts_value_type_check check (value_type in ('string', 'number', 'boolean', 'date', 'datetime', 'money', 'array', 'object', 'null')),
    constraint company_field_facts_source_not_blank check (btrim(source_provider) <> ''),
    constraint company_field_facts_confidence_check check (confidence is null or (confidence >= 0 and confidence <= 1)),
    constraint company_field_facts_validity_order check (valid_to is null or valid_from is null or valid_to >= valid_from),
    constraint company_field_facts_idempotency_not_blank check (btrim(idempotency_key) <> ''),
    constraint company_field_facts_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint company_field_facts_company_fkey foreign key (workspace_id, company_id) references public.companies(workspace_id, id) on delete restrict,
    constraint company_field_facts_source_record_fkey foreign key (workspace_id, source_record_id) references public.source_records(workspace_id, id) on delete restrict,
    constraint company_field_facts_source_snapshot_fkey foreign key (workspace_id, source_snapshot_id) references public.source_snapshots(workspace_id, id) on delete restrict,
    constraint company_field_facts_evidence_fkey foreign key (workspace_id, evidence_id) references public.company_evidence(workspace_id, id) on delete restrict
);

create unique index company_field_facts_one_current_source_idx
    on public.company_field_facts (workspace_id, company_id, field_name, source_provider)
    where is_current;

create index company_field_facts_current_company_idx
    on public.company_field_facts (workspace_id, company_id, field_name)
    where is_current;

create table public.risk_events (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    company_id bigint not null,
    risk_type text not null,
    severity text not null,
    title text not null,
    description text,
    event_status text not null default 'open',
    external_event_id text,
    amount numeric(20, 2),
    currency text not null default 'CNY',
    occurred_on date,
    resolved_on date,
    evidence_id uuid,
    source_provider text not null,
    idempotency_key text not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint risk_events_workspace_id_id_key unique (workspace_id, id),
    constraint risk_events_workspace_idempotency_key unique (workspace_id, idempotency_key),
    constraint risk_events_type_not_blank check (btrim(risk_type) <> ''),
    constraint risk_events_title_not_blank check (btrim(title) <> ''),
    constraint risk_events_severity_check check (severity in ('info', 'low', 'medium', 'high', 'critical')),
    constraint risk_events_status_check check (event_status in ('open', 'resolved', 'dismissed', 'unknown')),
    constraint risk_events_amount_nonnegative check (amount is null or amount >= 0),
    constraint risk_events_resolution_order check (resolved_on is null or occurred_on is null or resolved_on >= occurred_on),
    constraint risk_events_idempotency_not_blank check (btrim(idempotency_key) <> ''),
    constraint risk_events_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint risk_events_company_fkey foreign key (workspace_id, company_id) references public.companies(workspace_id, id) on delete restrict,
    constraint risk_events_evidence_fkey foreign key (workspace_id, evidence_id) references public.company_evidence(workspace_id, id) on delete restrict
);

create table public.qualifications (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    company_id bigint not null,
    qualification_type text not null,
    qualification_name text not null,
    certificate_number text,
    issuing_authority text,
    status text not null default 'unknown',
    issued_on date,
    expires_on date,
    evidence_id uuid,
    source_provider text not null,
    idempotency_key text not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint qualifications_workspace_id_id_key unique (workspace_id, id),
    constraint qualifications_workspace_idempotency_key unique (workspace_id, idempotency_key),
    constraint qualifications_type_not_blank check (btrim(qualification_type) <> ''),
    constraint qualifications_name_not_blank check (btrim(qualification_name) <> ''),
    constraint qualifications_status_check check (status in ('valid', 'expired', 'revoked', 'unknown')),
    constraint qualifications_expiry_order check (expires_on is null or issued_on is null or expires_on >= issued_on),
    constraint qualifications_idempotency_not_blank check (btrim(idempotency_key) <> ''),
    constraint qualifications_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint qualifications_company_fkey foreign key (workspace_id, company_id) references public.companies(workspace_id, id) on delete restrict,
    constraint qualifications_evidence_fkey foreign key (workspace_id, evidence_id) references public.company_evidence(workspace_id, id) on delete restrict
);

create table public.company_lists (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    name text not null,
    description text,
    status text not null default 'active',
    source_query_id uuid,
    ingestion_job_id uuid,
    created_via text not null default 'web_ui',
    created_by_agent text,
    agent_provider text,
    created_by uuid,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint company_lists_workspace_id_id_key unique (workspace_id, id),
    constraint company_lists_name_not_blank check (btrim(name) <> ''),
    constraint company_lists_status_check check (status in ('active', 'locked', 'archived')),
    constraint company_lists_created_via_check check (created_via in ('web_ui', 'workbuddy', 'agent', 'file_upload', 'api')),
    constraint company_lists_created_by_agent_not_blank check (created_by_agent is null or btrim(created_by_agent) <> ''),
    constraint company_lists_agent_provider_not_blank check (agent_provider is null or btrim(agent_provider) <> ''),
    constraint company_lists_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint company_lists_source_query_fkey foreign key (workspace_id, source_query_id) references public.source_queries(workspace_id, id) on delete restrict,
    constraint company_lists_ingestion_job_fkey foreign key (workspace_id, ingestion_job_id) references public.ingestion_jobs(workspace_id, id) on delete restrict,
    constraint company_lists_created_by_fkey foreign key (created_by) references auth.users(id) on delete set null
);

create unique index company_lists_workspace_name_idx
    on public.company_lists (workspace_id, lower(name));

create table public.company_list_members (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    company_list_id uuid not null,
    company_id bigint not null,
    source_record_id uuid,
    membership_status text not null default 'included',
    selection_reason jsonb not null default '[]'::jsonb,
    added_by uuid,
    added_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint company_list_members_workspace_id_id_key unique (workspace_id, id),
    constraint company_list_members_list_company_key unique (workspace_id, company_list_id, company_id),
    constraint company_list_members_status_check check (membership_status in ('included', 'excluded', 'needs_review')),
    constraint company_list_members_reason_array check (jsonb_typeof(selection_reason) = 'array'),
    constraint company_list_members_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint company_list_members_list_fkey foreign key (workspace_id, company_list_id) references public.company_lists(workspace_id, id) on delete restrict,
    constraint company_list_members_company_fkey foreign key (workspace_id, company_id) references public.companies(workspace_id, id) on delete restrict,
    constraint company_list_members_source_record_fkey foreign key (workspace_id, source_record_id) references public.source_records(workspace_id, id) on delete restrict,
    constraint company_list_members_added_by_fkey foreign key (added_by) references auth.users(id) on delete set null
);

create table public.rule_sets (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    name text not null,
    description text,
    business_objective text,
    status text not null default 'draft',
    current_version_number integer,
    created_by uuid,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint rule_sets_workspace_id_id_key unique (workspace_id, id),
    constraint rule_sets_workspace_name_key unique (workspace_id, name),
    constraint rule_sets_name_not_blank check (btrim(name) <> ''),
    constraint rule_sets_status_check check (status in ('draft', 'active', 'archived')),
    constraint rule_sets_version_positive check (current_version_number is null or current_version_number > 0),
    constraint rule_sets_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint rule_sets_created_by_fkey foreign key (created_by) references auth.users(id) on delete set null
);

create table public.rule_set_versions (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    rule_set_id uuid not null,
    version_number integer not null,
    status text not null default 'draft',
    rule_definition jsonb not null,
    scoring_definition jsonb not null default '{}'::jsonb,
    canonical_schema_version text not null default '1.0',
    change_note text,
    created_by uuid,
    created_at timestamp with time zone not null default now(),
    published_at timestamp with time zone,
    constraint rule_set_versions_workspace_id_id_key unique (workspace_id, id),
    constraint rule_set_versions_set_version_key unique (workspace_id, rule_set_id, version_number),
    constraint rule_set_versions_version_positive check (version_number > 0),
    constraint rule_set_versions_status_check check (status in ('draft', 'published', 'retired')),
    constraint rule_set_versions_definition_object check (jsonb_typeof(rule_definition) = 'object'),
    constraint rule_set_versions_scoring_object check (jsonb_typeof(scoring_definition) = 'object'),
    constraint rule_set_versions_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint rule_set_versions_rule_set_fkey foreign key (workspace_id, rule_set_id) references public.rule_sets(workspace_id, id) on delete restrict,
    constraint rule_set_versions_created_by_fkey foreign key (created_by) references auth.users(id) on delete set null
);

create table public.rule_runs (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    rule_version_id uuid not null,
    company_list_id uuid not null,
    run_mode text not null default 'full',
    status text not null default 'queued',
    engine_version text not null,
    input_manifest_hash text not null,
    run_config jsonb not null default '{}'::jsonb,
    idempotency_key text not null,
    requested_by uuid,
    requested_at timestamp with time zone not null default now(),
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    total_count integer not null default 0,
    included_count integer not null default 0,
    excluded_count integer not null default 0,
    review_count integer not null default 0,
    error_code text,
    error_message text,
    result jsonb not null default '{}'::jsonb,
    worker_id text,
    claimed_at timestamp with time zone,
    attempt_count integer not null default 0,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint rule_runs_workspace_id_id_key unique (workspace_id, id),
    constraint rule_runs_workspace_idempotency_key unique (workspace_id, idempotency_key),
    constraint rule_runs_mode_check check (run_mode in ('sample', 'full')),
    constraint rule_runs_status_check check (status in ('queued', 'running', 'completed', 'partial', 'failed', 'cancelled')),
    constraint rule_runs_hash_not_blank check (btrim(input_manifest_hash) <> ''),
    constraint rule_runs_config_object check (jsonb_typeof(run_config) = 'object'),
    constraint rule_runs_idempotency_format check (length(idempotency_key) between 16 and 128 and idempotency_key ~ '^[A-Za-z0-9._:-]+$'),
    constraint rule_runs_counts_nonnegative check (total_count >= 0 and included_count >= 0 and excluded_count >= 0 and review_count >= 0),
    constraint rule_runs_counts_consistent check (included_count + excluded_count + review_count <= total_count),
    constraint rule_runs_result_object check (jsonb_typeof(result) = 'object'),
    constraint rule_runs_attempt_count_nonnegative check (attempt_count >= 0),
    constraint rule_runs_time_order check (completed_at is null or started_at is null or completed_at >= started_at),
    constraint rule_runs_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint rule_runs_rule_version_fkey foreign key (workspace_id, rule_version_id) references public.rule_set_versions(workspace_id, id) on delete restrict,
    constraint rule_runs_company_list_fkey foreign key (workspace_id, company_list_id) references public.company_lists(workspace_id, id) on delete restrict,
    constraint rule_runs_requested_by_fkey foreign key (requested_by) references auth.users(id) on delete set null
);

create table public.rule_results (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    rule_run_id uuid not null,
    company_id bigint not null,
    decision text not null,
    score numeric(12, 4),
    matched_rules jsonb not null default '[]'::jsonb,
    failed_rules jsonb not null default '[]'::jsonb,
    missing_fields text[] not null default '{}',
    evaluated_values jsonb not null default '{}'::jsonb,
    result_hash text not null,
    evaluated_at timestamp with time zone not null default now(),
    created_at timestamp with time zone not null default now(),
    constraint rule_results_workspace_id_id_key unique (workspace_id, id),
    constraint rule_results_workspace_id_company_key unique (workspace_id, id, company_id),
    constraint rule_results_run_company_key unique (workspace_id, rule_run_id, company_id),
    constraint rule_results_decision_check check (decision in ('include', 'exclude', 'needs_review')),
    constraint rule_results_matched_rules_array check (jsonb_typeof(matched_rules) = 'array'),
    constraint rule_results_failed_rules_array check (jsonb_typeof(failed_rules) = 'array'),
    constraint rule_results_evaluated_values_object check (jsonb_typeof(evaluated_values) = 'object'),
    constraint rule_results_hash_not_blank check (btrim(result_hash) <> ''),
    constraint rule_results_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint rule_results_rule_run_fkey foreign key (workspace_id, rule_run_id) references public.rule_runs(workspace_id, id) on delete restrict,
    constraint rule_results_company_fkey foreign key (workspace_id, company_id) references public.companies(workspace_id, id) on delete restrict
);

create table public.manual_reviews (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    rule_result_id uuid not null,
    company_id bigint not null,
    reviewer_user_id uuid not null default auth.uid(),
    decision text not null,
    note text,
    is_current boolean not null default true,
    reviewed_at timestamp with time zone not null default now(),
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint manual_reviews_workspace_id_id_key unique (workspace_id, id),
    constraint manual_reviews_decision_check check (decision in ('approve', 'reject', 'needs_information')),
    constraint manual_reviews_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint manual_reviews_rule_result_company_fkey foreign key (workspace_id, rule_result_id, company_id) references public.rule_results(workspace_id, id, company_id) on delete restrict,
    constraint manual_reviews_reviewer_fkey foreign key (reviewer_user_id) references auth.users(id) on delete restrict
);

create unique index manual_reviews_one_current_idx
    on public.manual_reviews (workspace_id, rule_result_id)
    where is_current;

create table public.exports (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    company_list_id uuid,
    rule_run_id uuid,
    export_format text not null,
    status text not null default 'queued',
    selected_fields text[] not null default '{}',
    filter_definition jsonb not null default '{}'::jsonb,
    storage_bucket text,
    storage_path text,
    checksum_sha256 text,
    file_size_bytes bigint,
    row_count integer,
    idempotency_key text not null,
    requested_by uuid,
    requested_at timestamp with time zone not null default now(),
    completed_at timestamp with time zone,
    expires_at timestamp with time zone,
    error_code text,
    error_message text,
    result jsonb not null default '{}'::jsonb,
    worker_id text,
    claimed_at timestamp with time zone,
    attempt_count integer not null default 0,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint exports_workspace_id_id_key unique (workspace_id, id),
    constraint exports_workspace_idempotency_key unique (workspace_id, idempotency_key),
    constraint exports_scope_present check (num_nonnulls(company_list_id, rule_run_id) >= 1),
    constraint exports_format_check check (export_format in ('csv', 'xlsx', 'json', 'html')),
    constraint exports_status_check check (status in ('queued', 'running', 'completed', 'failed', 'expired', 'cancelled')),
    constraint exports_filter_object check (jsonb_typeof(filter_definition) = 'object'),
    constraint exports_result_object check (jsonb_typeof(result) = 'object'),
    constraint exports_file_size_nonnegative check (file_size_bytes is null or file_size_bytes >= 0),
    constraint exports_row_count_nonnegative check (row_count is null or row_count >= 0),
    constraint exports_idempotency_format check (length(idempotency_key) between 16 and 128 and idempotency_key ~ '^[A-Za-z0-9._:-]+$'),
    constraint exports_attempt_count_nonnegative check (attempt_count >= 0),
    constraint exports_expiry_order check (expires_at is null or completed_at is null or expires_at >= completed_at),
    constraint exports_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint exports_company_list_fkey foreign key (workspace_id, company_list_id) references public.company_lists(workspace_id, id) on delete restrict,
    constraint exports_rule_run_fkey foreign key (workspace_id, rule_run_id) references public.rule_runs(workspace_id, id) on delete restrict,
    constraint exports_requested_by_fkey foreign key (requested_by) references auth.users(id) on delete set null
);

create unique index exports_storage_object_idx
    on public.exports (workspace_id, storage_bucket, storage_path)
    where storage_bucket is not null and storage_path is not null;

create table public.company_reports (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    company_id bigint not null,
    evidence_job_id uuid not null,
    source_snapshot_id uuid not null,
    revision integer not null,
    status text not null default 'completed',
    schema_version text not null default 'company-agent-analysis.v1',
    agent_provider text not null,
    agent_name text not null,
    analysis jsonb not null,
    is_current boolean not null default true,
    submitted_by uuid,
    submitted_at timestamp with time zone not null default now(),
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint company_reports_workspace_id_id_key unique (workspace_id, id),
    constraint company_reports_job_revision_key unique (workspace_id, evidence_job_id, revision),
    constraint company_reports_revision_positive check (revision > 0),
    constraint company_reports_status_check check (status in ('completed', 'superseded')),
    constraint company_reports_schema_check check (schema_version = 'company-agent-analysis.v1'),
    constraint company_reports_agent_provider_check check (length(agent_provider) between 2 and 64 and agent_provider ~ '^[a-z0-9][a-z0-9._-]*$'),
    constraint company_reports_agent_name_check check (length(btrim(agent_name)) between 1 and 120 and agent_name !~ '[[:cntrl:]]'),
    constraint company_reports_analysis_object check (jsonb_typeof(analysis) = 'object'),
    constraint company_reports_analysis_size check (octet_length(analysis::text) <= 131072),
    constraint company_reports_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint company_reports_company_fkey foreign key (workspace_id, company_id) references public.companies(workspace_id, id) on delete restrict,
    constraint company_reports_job_fkey foreign key (workspace_id, evidence_job_id) references public.ingestion_jobs(workspace_id, id) on delete restrict,
    constraint company_reports_snapshot_fkey foreign key (workspace_id, source_snapshot_id) references public.source_snapshots(workspace_id, id) on delete restrict,
    constraint company_reports_submitted_by_fkey foreign key (submitted_by) references auth.users(id) on delete set null
);

create unique index company_reports_one_current_job_idx
    on public.company_reports (workspace_id, evidence_job_id)
    where is_current;

create index company_reports_company_recent_idx
    on public.company_reports (workspace_id, company_id, submitted_at desc);

create table public.audit_logs (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null,
    actor_type text not null,
    actor_user_id uuid,
    actor_label text,
    action text not null,
    entity_type text not null,
    entity_id text,
    request_id text,
    trace_id text,
    source_ip inet,
    user_agent text,
    before_data jsonb,
    after_data jsonb,
    metadata jsonb not null default '{}'::jsonb,
    occurred_at timestamp with time zone not null default now(),
    created_at timestamp with time zone not null default now(),
    constraint audit_logs_workspace_id_id_key unique (workspace_id, id),
    constraint audit_logs_actor_type_check check (actor_type in ('user', 'service', 'agent', 'system')),
    constraint audit_logs_action_not_blank check (btrim(action) <> ''),
    constraint audit_logs_entity_type_not_blank check (btrim(entity_type) <> ''),
    constraint audit_logs_metadata_object check (jsonb_typeof(metadata) = 'object'),
    constraint audit_logs_workspace_fkey foreign key (workspace_id) references public.workspaces(id) on delete restrict,
    constraint audit_logs_actor_user_fkey foreign key (actor_user_id) references auth.users(id) on delete set null
);

-- Tenant-leading indexes used by PostgREST list/filter operations and workers.
create index field_mapping_sets_workspace_status_idx on public.field_mapping_sets (workspace_id, status, updated_at desc);
create index field_mapping_versions_set_created_idx on public.field_mapping_versions (workspace_id, mapping_set_id, created_at desc);
create index source_connections_workspace_status_idx on public.source_connections (workspace_id, status, provider);
create index source_queries_workspace_status_idx on public.source_queries (workspace_id, status, created_at desc);
create index ingestion_jobs_workspace_status_idx on public.ingestion_jobs (workspace_id, status, requested_at desc);
create index ingestion_jobs_queue_claim_idx on public.ingestion_jobs (requested_at, id) where status = 'queued';
create index source_records_workspace_captured_idx on public.source_records (workspace_id, captured_at desc);
create index source_records_content_hash_idx on public.source_records (workspace_id, content_hash);
create index source_snapshots_company_captured_idx on public.source_snapshots (workspace_id, company_id, captured_at desc);
create index company_evidence_company_captured_idx on public.company_evidence (workspace_id, company_id, captured_at desc);
create index risk_events_company_severity_idx on public.risk_events (workspace_id, company_id, severity, occurred_on desc);
create index qualifications_company_expiry_idx on public.qualifications (workspace_id, company_id, expires_on);
create index company_list_members_list_status_idx on public.company_list_members (workspace_id, company_list_id, membership_status);
create index rule_sets_workspace_status_idx on public.rule_sets (workspace_id, status, updated_at desc);
create index rule_runs_workspace_status_idx on public.rule_runs (workspace_id, status, requested_at desc);
create index rule_runs_queue_claim_idx on public.rule_runs (requested_at, id) where status = 'queued';
create index rule_results_run_decision_idx on public.rule_results (workspace_id, rule_run_id, decision, score desc);
create index manual_reviews_workspace_recent_idx on public.manual_reviews (workspace_id, reviewed_at desc);
create index exports_workspace_status_idx on public.exports (workspace_id, status, requested_at desc);
create index exports_queue_claim_idx on public.exports (requested_at, id) where status = 'queued';
create index company_reports_workspace_status_idx on public.company_reports (workspace_id, status, submitted_at desc);
create index audit_logs_workspace_time_idx on public.audit_logs (workspace_id, occurred_at desc);
create index audit_logs_entity_idx on public.audit_logs (workspace_id, entity_type, entity_id, occurred_at desc);
