name: ✅ Check
on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    lint:
        name: 🔬 ESLint
        permissions:
            contents: read
            checks: write
        runs-on: ubuntu-latest
        timeout-minutes: 10
        if: ${{ !github.event.pull_request.draft || github.event_name == 'push' }}
        steps:
            - name: 📥 Checkout repo
              uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

            - name: ⚙️ Setup node
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
              with:
                  node-version: 22
                  cache: npm

            - name: 📥 Download deps
              run: npm ci

            - name: 🔬 Lint
              uses: wearerequired/lint-action@548d8a7c4b04d3553d32ed5b6e91eb171e10e7bb # v2
              with:
                  eslint: true
                  eslint_args: "**/*.{mjs,ts,tsx}"
                  prettier: true
                  prettier_args: "--config ./.prettierrc.json \"**/*.{js,json,ts,tsx,css,md,html}\""


    typecheck:
        name: 🏷️ Typecheck
        timeout-minutes: 10
        runs-on: ubuntu-latest
        if: ${{ !github.event.pull_request.draft || github.event_name == 'push' }}
        steps:
            - name: 📥 Checkout repo
              uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

            - name: ⚙️ Setup node
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
              with:
                  node-version: 22
                  cache: npm

            - name: 📥 Download deps
              run: npm ci

            - name: 🏷️ Typecheck
              run: npm run typecheck
              
    test-app:
        name: 🔎 Test
        runs-on: ubuntu-latest
        timeout-minutes: 10
        if: ${{ !github.event.pull_request.draft || github.event_name == 'push' }}
        steps:
            - name: 📥 Checkout repo
              uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

            - name: ⚙️ Setup node
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
              with:
                  node-version: 22
                  cache: npm

            - name: 📥 Download deps
              run: npm ci

            - name: 🎭 Install Playwright browsers
              run: npx playwright install chromium-headless-shell 1>/dev/null

            - name: 🔎 Unit Tests on App
              run: CI=1 npm run test:unit:app -- --run
            - name: 🔎 Unit Tests on Supabase functions
              run: CI=1 npm run test:unit:functions -- --run

    e2e-test:
      timeout-minutes: 10
      runs-on: ubuntu-latest
      steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: ⚙️ Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
            node-version: 22
            cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium-headless-shell 1>/dev/null
      - name: Install wait-on and serve
        run: npm install -g wait-on serve
      - name: Run Playwright tests
        run: make test-e2e-ci

    build:
        name: 🔨 Build
        timeout-minutes: 10
        runs-on: ubuntu-latest
        if: ${{ !github.event.pull_request.draft || github.event_name == 'push' }}
        steps:
            - name: 📥 Checkout repo
              uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

            - name: ⚙️ Setup node
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
              with:
                  node-version: 22
                  cache: npm

            - name: 📥 Download deps
              run: npm ci

            - name: 🔨 Build
              run: npm run build
